LLM_CHOICES = ["llama3.2:1b-instruct-fp16", "gemma2:2b"]
DEFAULT_LLM_CHOICE = "gemma2:2b"
DEFAULT_LLM_IDX = LLM_CHOICES.index(DEFAULT_LLM_CHOICE)

EMBEDDING_CHOICES = ["nomic-embed-text:latest"]
DEFAULT_EMBEDDING_CHOICE = "nomic-embed-text:latest"
DEFAULT_EMBEDDING_IDX = EMBEDDING_CHOICES.index(DEFAULT_EMBEDDING_CHOICE)

CHROMA_COLLECTION_NAME = 'rag'
